title: Spinning Numbers


description: > # this means to ignore newlines until "baseurl:"
  Learn electrical engineering.  
markdown: kramdown


# Staticman comments
#staticmanUrl: https://api.staticman.net/v3/entry/github/willymcallister/willymcallister.github.io/master/comments

# reCAPTCHA keys
reCaptcha:
  siteKey: "6LcK3xkUAAAAAKdppIIORt78Df93D2qvOGtZinEy"
  secret: "XQ/rrrBv4ejks8vjcdcjffukZoOC30fMuX0F7QVlE2iKp6irA5QFl8lN5UQjzG41stle2JgzU8AMv40aaGdH0S9A4OpUxJTjCEQpHPtKsWOIyncB0rV7ztWoA+88dt9ywmF9hk8AuKxSxNrf1YHJ73hesMeCsFmZE3CCeAozRce6Oaox1kZ+tYu5R0Kx+2zu0GARFrwz4pzVanwPKAwn6m7P4BRN+QJcQtCQjuFRd3T9XyWmm0JzEqnrTa5XczkCjsXU7SgoEZPKyuG3ercW87t1fgUPGydJrSS9rsKEyy3RJfqZZC8LT63uATM4M/CAdVrP7gjZMI3VkwPY/WB/ikEhcSgl9ONe1b1ySWE6YCbEAxfbChmBqNGdLeZRXoQQHEfFgDtrkn2QC/UlyXuy9x7XAsM0mbJqyERSJdmnAM3RLXUjc7o4LNfsmbcZFLxduqyLmNDW1LUbWA12Q/Am/CC1BRqhZlaHoa9Ep90KX+EivOlxZk5/WyTVFbeczFeKz64Eu53yosxrgc6GrEFZOlJCCYYeXnBbElU7P144KGSstO1ahbwPBD1VzPpJNRysq4yzJFOL3DPfPdi2E1GnPmHy/5Jb+pBRMxi5S46yyXTpD0pD183GU6npoRNsDnJt03Yb2zkURpaMjpYkrimE7USGuGgrx4wauX1XNxQ+6tA="


staticman:
  api: "https://anasbasem.herokuapp.com/v2/entry/basemwahba/anas/master/comments"
  path: "_data/comments"
